//
//  AppDelegate.h
//  GGTalk
//
//  Created by lee yee chuan on 3/7/14.
//  Copyright (c) 2014 lee yee chuan. All rights reserved.
//

#import <UIKit/UIKit.h>

#define INIT_BEACON_FAILED_ALERT_VIEW_DONT_SHOW_AGAIN (@"INIT_BEACON_FAILED_ALERT_VIEW_DONT_SHOW_AGAIN")
#define DELETE_BEACON_FAILED_ALERT_VIEW_DONT_SHOW_AGAIN (@"DELETE_BEACON_FAILED_ALERT_VIEW_DONT_SHOW_AGAIN")
#define ADVERTISING_BEACON_FAILED_ALERT_VIEW_DONT_SHOW_AGAIN (@"ADVERTISING_BEACON_FAILED_ALERT_VIEW_DONT_SHOW_AGAIN")
#define WARN_BROADCAST_MUST_FOREGROUND_ALERT_VIEW_DONT_SHOW_AGAIN (@"WARN_BROADCAST_MUST_FOREGROUND_ALERT_VIEW_DONT_SHOW_AGAIN")

@interface AppDelegate : UIResponder <UIApplicationDelegate>

@property (strong, nonatomic) UIWindow *window;
@end
